# Generated by Django 3.0.4 on 2020-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
