# Generated by Django 3.0.4 on 2020-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
