# Generated by Django 3.0.4 on 2020-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0002_auto_20200620_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.TextField(),
        ),
    ]
