# Generated by Django 3.0.4 on 2020-06-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0004_auto_20200625_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordsafe',
            name='owner',
        ),
    ]
