# Generated by Django 3.0.4 on 2020-06-25 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safe', '0005_remove_passwordsafe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordsafe',
            name='owner',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
